# Generated by Django 4.2.6 on 2023-10-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_and_tags', '0002_alter_task_deadline_alter_task_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
